// countries.js
export const countries = [
  { value: 1, ar: "جزيرة أسنسيون", en: "Ascension Island" },
  { value: 2, ar: "أندورا", en: "Andorra" },
  { value: 3, ar: "الامارات العربية المتحدة", en: "United Arab Emirates" },
  { value: 4, ar: "أفغانستان", en: "Afghanistan" },
  { value: 5, ar: "انتيغوا وبربودا", en: "Antigua and Barbuda" },
  { value: 6, ar: "أنغيلا", en: "Anguilla" },
  { value: 7, ar: "ألبانيا", en: "Albania" },
  { value: 8, ar: "أرمينيا", en: "Armenia" },
  { value: 9, ar: "جزر الأنتيل الهولندية", en: "Netherlands Antilles" },
  { value: 10, ar: "أنغولا", en: "Angola" },
  { value: 11, ar: "القارة القطبية الجنوبية", en: "Antarctica" },
  { value: 12, ar: "الأرجنتين", en: "Argentina" },
  { value: 13, ar: "ساموا الأمريكية", en: "American Samoa" },
  { value: 14, ar: "النمسا", en: "Austria" },
  { value: 15, ar: "أستراليا", en: "Australia" },
  { value: 16, ar: "أروبا", en: "Aruba" },
  { value: 17, ar: "جزر آلاند", en: "Aland Islands" },
  { value: 18, ar: "أذربيجان", en: "Azerbaijan" },
  { value: 19, ar: "البوسنة والهرسك", en: "Bosnia and Herzegovina" },
  { value: 20, ar: "بربادوس", en: "Barbados" },
  { value: 21, ar: "بنجلاديش", en: "Bangladesh" },
  { value: 22, ar: "بلجيكا", en: "Belgium" },
  { value: 23, ar: "بوركينا فاسو", en: "Burkina Faso" },
  { value: 24, ar: "بلغاريا", en: "Bulgaria" },
  { value: 25, ar: "البحرين", en: "Bahrain" },
  { value: 26, ar: "بوروندي", en: "Burundi" },
  { value: 27, ar: "بنين", en: "Benin" },
  { value: 28, ar: "سانت بارتيليمي", en: "Saint Barthélemy" },
  { value: 29, ar: "برمودا", en: "Bermuda" },
  { value: 30, ar: "بروناي", en: "Brunei" },
  { value: 31, ar: "بوليفيا", en: "Bolivia" },
  { value: 32, ar: "الأراضي القطبية الجنوبية البريطانية", en: "British Antarctic Territory" },
  { value: 33, ar: "البرازيل", en: "Brazil" },
  { value: 34, ar: "جزر البهاما", en: "Bahamas" },
  { value: 35, ar: "بوتان", en: "Bhutan" },
  { value: 36, ar: "جزيرة بوفيه", en: "Bouvet Island" },
  { value: 37, ar: "بوتسوانا", en: "Botswana" },
  { value: 38, ar: "روسيا البيضاء", en: "Belarus" },
  { value: 39, ar: "بليز", en: "Belize" },
  { value: 40, ar: "كندا", en: "Canada" },
  { value: 41, ar: "جزر كوكوس", en: "Cocos [Keeling] Islands" },
  { value: 42, ar: "جمهورية الكونغو الديمقراطية", en: "Congo - Kinshasa" },
  { value: 43, ar: "جمهورية افريقيا الوسطى", en: "Central African Republic" },
  { value: 44, ar: "الكونغو - برازافيل", en: "Congo - Brazzaville" },
  { value: 45, ar: "سويسرا", en: "Switzerland" },
  { value: 46, ar: "ساحل العاج", en: "Côte d’Ivoire" },
  { value: 47, ar: "جزر كوك", en: "Cook Islands" },
  { value: 48, ar: "تشيلي", en: "Chile" },
  { value: 49, ar: "الكاميرون", en: "Cameroon" },
  { value: 50, ar: "الصين", en: "China" },
  { value: 51, ar: "كولومبيا", en: "Colombia" },
  { value: 52, ar: "جزيرة كليبرتون", en: "Clipperton Island" },
  { value: 53, ar: "كوستاريكا", en: "Costa Rica" },
  { value: 54, ar: "صربيا والجبل الأسود", en: "Serbia and Montenegro" },
  { value: 55, ar: "كانتون وجزر اندربوري", en: "Canton and Enderbury Islands" },
  { value: 56, ar: "كوبا", en: "Cuba" },
  { value: 57, ar: "الرأس الأخضر", en: "Cape Verde" },
  { value: 58, ar: "جزيرة الكريسماس", en: "Christmas Island" },
  { value: 59, ar: "قبرص", en: "Cyprus" },
  { value: 60, ar: "جمهورية التشيك", en: "Czech Republic" },
  { value: 61, ar: "شرق ألمانيا", en: "East Germany" },
  { value: 62, ar: "ألمانيا", en: "Germany" },
  { value: 63, ar: "دييغو غارسيا", en: "Diego Garcia" },
  { value: 64, ar: "جيبوتي", en: "Djibouti" },
  { value: 65, ar: "الدنمارك", en: "Denmark" },
  { value: 66, ar: "دومينيكا", en: "Dominica" },
  { value: 67, ar: "جمهورية الدومينيك", en: "Dominican Republic" },
  { value: 68, ar: "الجزائر", en: "Algeria" },
  { value: 69, ar: "سيوتا وميليلا", en: "Ceuta and Melilla" },
  { value: 70, ar: "الاكوادور", en: "Ecuador" },
  { value: 71, ar: "استونيا", en: "Estonia" },
  { value: 72, ar: "مصر", en: "Egypt" },
  { value: 73, ar: "الصحراء الغربية", en: "Western Sahara" },
  { value: 74, ar: "اريتريا", en: "Eritrea" },
  { value: 75, ar: "إسبانيا", en: "Spain" },
  { value: 76, ar: "أثيوبيا", en: "Ethiopia" },
  { value: 77, ar: "الاتحاد الاوروبي", en: "European Union" },
  { value: 78, ar: "فنلندا", en: "Finland" },
  { value: 79, ar: "فيجي", en: "Fiji" },
  { value: 80, ar: "جزر فوكلاند", en: "Falkland Islands" },
  { value: 81, ar: "ميكرونيزيا", en: "Micronesia" },
  { value: 82, ar: "جزر فارو", en: "Faroe Islands" },
  { value: 83, ar: "فرنسا والاراضي القطبية الجنوبية", en: "French Southern and Antarctic Territories" },
  { value: 84, ar: "فرنسا", en: "France" },
  { value: 85, ar: "متروبوليتان فرنسا", en: "Metropolitan France" },
  { value: 86, ar: "الجابون", en: "Gabon" },
  { value: 87, ar: "المملكة المتحدة", en: "United Kingdom" },
  { value: 88, ar: "غرينادا", en: "Grenada" },
  { value: 89, ar: "جورجيا", en: "Georgia" },
  { value: 90, ar: "جويانا الفرنسية", en: "French Guiana" },
  { value: 91, ar: "غيرنسي", en: "Guernsey" },
  { value: 92, ar: "غانا", en: "Ghana" },
  { value: 93, ar: "جبل طارق", en: "Gibraltar" },
  { value: 94, ar: "غرينلاند", en: "Greenland" },
  { value: 95, ar: "غامبيا", en: "Gambia" },
  { value: 96, ar: "غينيا", en: "Guinea" },
  { value: 97, ar: "جوادلوب", en: "Guadeloupe" },
  { value: 98, ar: "غينيا الاستوائية", en: "Equatorial Guinea" },
  { value: 99, ar: "يونان", en: "Greece" },
  { value: 100, ar: "جورجيا الجنوبية وجزر ساندويتش الجنوبية", en: "South Georgia and the South Sandwich Islands" },
   { value: "101", ar: "غواتيمالا", en: "Guatemala" },
  { value: "102", ar: "غوام", en: "Guam" },
  { value: "103", ar: "غينيا بيساو", en: "Guinea-Bissau" },
  { value: "104", ar: "غيانا", en: "Guyana" },
  { value: "105", ar: "هونغ كونغ الصين", en: "Hong Kong SAR China" },
  { value: "106", ar: "جزيرة هيرد وجزر ماكدونالد", en: "Heard Island and McDonald Islands" },
  { value: "107", ar: "هندوراس", en: "Honduras" },
  { value: "108", ar: "كرواتيا", en: "Croatia" },
  { value: "109", ar: "هايتي", en: "Haiti" },
  { value: "110", ar: "هنغاريا", en: "Hungary" },
  { value: "111", ar: "جزر الكناري", en: "Canary Islands" },
  { value: "112", ar: "أندونيسيا", en: "Indonesia" },
  { value: "113", ar: "أيرلندا", en: "Ireland" },
  { value: "114", ar: "جزيرة مان", en: "Isle of Man" },
  { value: "115", ar: "الهند", en: "India" },
  { value: "116", ar: "إقليم المحيط الهندي البريطاني", en: "British Indian Ocean Territory" },
  { value: "117", ar: "العراق", en: "Iraq" },
  { value: "118", ar: "ايران", en: "Iran" },
  { value: "119", ar: "أيسلندا", en: "Iceland" },
  { value: "120", ar: "إيطاليا", en: "Italy" },
  { value: "121", ar: "جيرسي", en: "Jersey" },
  { value: "122", ar: "جامايكا", en: "Jamaica" },
  { value: "123", ar: "الأردن", en: "Jordan" },
  { value: "124", ar: "اليابان", en: "Japan" },
  { value: "125", ar: "جزيرة جونستون", en: "Johnston Island" },
  { value: "126", ar: "كينيا", en: "Kenya" },
  { value: "127", ar: "قرغيزستان", en: "Kyrgyzstan" },
  { value: "128", ar: "كمبوديا", en: "Cambodia" },
  { value: "129", ar: "كيريباتي", en: "Kiribati" },
  { value: "130", ar: "جزر القمر", en: "Comoros" },
  { value: "131", ar: "سانت كيتس ونيفيس", en: "Saint Kitts and Nevis" },
  { value: "132", ar: "كوريا الشمالية", en: "North Korea" },
  { value: "133", ar: "كوريا الجنوبية", en: "South Korea" },
  { value: "134", ar: "الكويت", en: "Kuwait" },
  { value: "135", ar: "جزر كايمان", en: "Cayman Islands" },
  { value: "136", ar: "كازاخستان", en: "Kazakhstan" },
  { value: "137", ar: "لاوس", en: "Laos" },
  { value: "138", ar: "لبنان", en: "Lebanon" },
  { value: "139", ar: "سانت لوسيا", en: "Saint Lucia" },
  { value: "140", ar: "ليختنشتاين", en: "Liechtenstein" },
  { value: "141", ar: "سيريلانكا", en: "Sri Lanka" },
  { value: "142", ar: "ليبيريا", en: "Liberia" },
  { value: "143", ar: "ليسوتو", en: "Lesotho" },
  { value: "144", ar: "ليتوانيا", en: "Lithuania" },
  { value: "145", ar: "لوكسمبورغ", en: "Luxembourg" },
  { value: "146", ar: "لاتفيا", en: "Latvia" },
  { value: "147", ar: "ليبيا", en: "Libya" },
  { value: "148", ar: "المغرب", en: "Morocco" },
  { value: "149", ar: "موناكو", en: "Monaco" },
  { value: "150", ar: "مولدافيا", en: "Moldova" },
  { value: "151", ar: "الجبل الأسود", en: "Montenegro" },
  { value: "152", ar: "سانت مارتن", en: "Saint Martin" },
  { value: "153", ar: "مدغشقر", en: "Madagascar" },
  { value: "154", ar: "جزر مارشال", en: "Marshall Islands" },
  { value: "155", ar: "جزر منتصف الطريق", en: "Midway Islands" },
  { value: "156", ar: "مقدونيا", en: "Macedonia" },
  { value: "157", ar: "مالي", en: "Mali" },
  { value: "158", ar: "ميانمار (بورما)", en: "Myanmar [Burma]" },
  { value: "159", ar: "منغوليا", en: "Mongolia" },
  { value: "160", ar: "ماكاو الصينية", en: "Macau SAR China" },
  { value: "161", ar: "جزر ماريانا الشمالية", en: "Northern Mariana Islands" },
  { value: "162", ar: "مارتينيك", en: "Martinique" },
  { value: "163", ar: "موريتانيا", en: "Mauritania" },
  { value: "164", ar: "مونتسيرات", en: "Montserrat" },
  { value: "165", ar: "مالطا", en: "Malta" },
  { value: "167", ar: "موريشيوس", en: "Mauritius" },
  { value: "168", ar: "جزر المالديف", en: "Maldives" },
  { value: "169", ar: "ملاوي", en: "Malawi" },
  { value: "170", ar: "المكسيك", en: "Mexico" },
  { value: "171", ar: "ماليزيا", en: "Malaysia" },
  { value: "172", ar: "موزمبيق", en: "Mozambique" },
  { value: "173", ar: "ناميبيا", en: "Namibia" },
  { value: "174", ar: "كاليدونيا الجديدة", en: "New Caledonia" },
  { value: "175", ar: "النيجر", en: "Niger" },
  { value: "176", ar: "جزيرة نورفولك", en: "Norfolk Island" },
  { value: "177", ar: "نيجيريا", en: "Nigeria" },
  { value: "178", ar: "نيكاراغوا", en: "Nicaragua" },
  { value: "179", ar: "هولندا", en: "Netherlands" },
  { value: "180", ar: "النرويج", en: "Norway" },
  { value: "181", ar: "نيبال", en: "Nepal" },
  { value: "182", ar: "مود لاند", en: "Dronning Maud Land" },
  { value: "183", ar: "ناورو", en: "Nauru" },
  { value: "184", ar: "المنطقة المحايدة", en: "Neutral Zone" },
  { value: "185", ar: "نيوي", en: "Niue" },
  { value: "186", ar: "نيوزيلندا", en: "New Zealand" },
  { value: "187", ar: "عمان", en: "Oman" },
  { value: "188", ar: "بنما", en: "Panama" },
  { value: "189", ar: "جزر المحيط الهادي الثقة الأرض", en: "Pacific Islands Trust Territory" },
  { value: "190", ar: "بيرو", en: "Peru" },
  { value: "191", ar: "بولينيزيا الفرنسية", en: "French Polynesia" },
  { value: "192", ar: "بابوا غينيا الجديدة", en: "Papua New Guinea" },
  { value: "193", ar: "الفلبين", en: "Philippines" },
  { value: "194", ar: "باكستان", en: "Pakistan" },
  { value: "195", ar: "بولندا", en: "Poland" },
  { value: "196", ar: "سان بيار وميكلون", en: "Saint Pierre and Miquelon" },
  { value: "197", ar: "جزر بيتكيرن", en: "Pitcairn Islands" },
  { value: "198", ar: "بورتوريكو", en: "Puerto Rico" },
  { value: "199", ar: "فلسطين", en: "Palestine" },
  { value: "200", ar: "البرتغال", en: "Portugal" },
  { value: "201", ar: "الولايات المتحدة متنوعة جزر المحيط الهادئ", en: "U.S. Miscellaneous Pacific Islands" },
  { value: "202", ar: "بالاو", en: "Palau" },
  { value: "203", ar: "باراغواي", en: "Paraguay" },
  { value: "204", ar: "منطقة قناة بنما", en: "Panama Canal Zone" },
  { value: "205", ar: "قطر", en: "Qatar" },
  { value: "206", ar: "أوقيانوسيا النائية", en: "Outlying Oceania" },
  { value: "207", ar: "ريونيون", en: "Réunion" },
  { value: "208", ar: "رومانيا", en: "Romania" },
  { value: "209", ar: "صربيا", en: "Serbia" },
  { value: "210", ar: "روسيا", en: "Russia" },
  { value: "211", ar: "رواندا", en: "Rwanda" },
  { value: "213", ar: "المملكة العربية السعودية", en: "Saudi Arabia" },
  { value: "214", ar: "جزر سليمان", en: "Solomon Islands" },
  { value: "215", ar: "سيشل", en: "Seychelles" },
  { value: "216", ar: "سودان", en: "Sudan" },
  { value: "217", ar: "السويد", en: "Sweden" },
  { value: "218", ar: "سنغافورة", en: "Singapore" },
  { value: "219", ar: "سانت هيلانة", en: "Saint Helena" },
  { value: "220", ar: "سلوفينيا", en: "Slovenia" },
  { value: "221", ar: "سفالبارد وجان مايان", en: "Svalbard and Jan Mayen" },
  { value: "222", ar: "سلوفاكيا", en: "Slovakia" },
  { value: "223", ar: "سيراليون", en: "Sierra Leone" },
  { value: "224", ar: "سان مارينو", en: "San Marino" },
  { value: "225", ar: "السنغال", en: "Senegal" },
  { value: "226", ar: "الصومال", en: "Somalia" },
  { value: "227", ar: "سورينام", en: "Suriname" },
  { value: "228", ar: "ساو تومي وبرينسيبي", en: "São Tomé and Príncipe" },
  { value: "229", ar: "اتحاد الجمهوريات الاشتراكية السوفياتية", en: "Union of Soviet Socialist Republics" },
  { value: "230", ar: "السلفادور", en: "El Salvador" },
  { value: "231", ar: "سوريا", en: "Syria" },
  { value: "232", ar: "سوازيلاند", en: "Swaziland" },
  { value: "233", ar: "تريستان دا كونها", en: "Tristan da Cunha" },
  { value: "234", ar: "جزر تركس وكايكوس", en: "Turks and Caicos Islands" },
  { value: "235", ar: "تشاد", en: "Chad" },
  { value: "236", ar: "الأقاليم الجنوبية الفرنسية", en: "French Southern Territories" },
  { value: "237", ar: "توغو", en: "Togo" },
  { value: "238", ar: "تايلاند", en: "Thailand" },
  { value: 239, ar: "طاجيكستان", en: "Tajikistan" },
  { value: 240, ar: "توكيلاو", en: "Tokelau" },
  { value: 241, ar: "تيمور الشرقية", en: "Timor-Leste" },
  { value: 242, ar: "تركمانستان", en: "Turkmenistan" },
  { value: 243, ar: "تونس", en: "Tunisia" },
  { value: 244, ar: "تونغا", en: "Tonga" },
  { value: 245, ar: "تركيا", en: "Turkey" },
  { value: 246, ar: "ترينيداد وتوباغو", en: "Trinidad and Tobago" },
  { value: 247, ar: "توفالو", en: "Tuvalu" },
  { value: 248, ar: "تايوان الصينية", en: "Chinese Taiwan" },
  { value: 249, ar: "تنزانيا", en: "Tanzania" },
  { value: 250, ar: "أوكرانيا", en: "Ukraine" },
  { value: 251, ar: "أوغندا", en: "Uganda" },
  { value: 252, ar: "الولايات المتحدة البعيدة الصغيرة جزر", en: "U.S. Minor Outlying Islands" },
  { value: 253, ar: "الولايات المتحدة", en: "United States" },
  { value: 254, ar: "أوروغواي", en: "Uruguay" },
  { value: 255, ar: "أوزبكستان", en: "Uzbekistan" },
  { value: 256, ar: "مدينة الفاتيكان", en: "Vatican City" },
  { value: 257, ar: "سانت فنسنت وغرينادين", en: "Saint Vincent and the Grenadines" },
  { value: 258, ar: "شمال فيتنام", en: "North Vietnam" },
  { value: 259, ar: "فنزويلا", en: "Venezuela" },
  { value: 260, ar: "الجزر البريطانية العذراء", en: "British Virgin Islands" },
  { value: 261, ar: "الجزر الامريكية العذراء", en: "U.S. Virgin Islands" },
  { value: 262, ar: "فيتنام", en: "Vietnam" },
  { value: 263, ar: "فانواتو", en: "Vanuatu" },
  { value: 264, ar: "واليس وفوتونا", en: "Wallis and Futuna" },
  { value: 265, ar: "جزيرة ويك", en: "Wake Island" },
  { value: 266, ar: "ساموا", en: "Samoa" },
  { value: 267, ar: "جمهورية اليمن الديمقراطية", en: "People's Democratic Republic of Yemen" },
  { value: 268, ar: "اليمن", en: "Yemen" },
  { value: 269, ar: "مايوت", en: "Mayotte" },
  { value: 270, ar: "جنوب أفريقيا", en: "South Africa" },
  { value: 271, ar: "زامبيا", en: "Zambia" },
  { value: 272, ar: "زيمبابوي", en: "Zimbabwe" },
  { value: 273, ar: "غير معروف المنطقة", en: "Unknown Region" },
  { value: 1906, ar: "اسرائيل", en: "Israel" },
];


export default countries;